/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportMovingRouteImport } from './routes/transport-moving'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as EmergencyServicesRouteImport } from './routes/emergency-services'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TransportMovingRoute = TransportMovingRouteImport.update({
  id: '/transport-moving',
  path: '/transport-moving',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyServicesRoute = EmergencyServicesRouteImport.update({
  id: '/emergency-services',
  path: '/emergency-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emergency-services': typeof EmergencyServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/transport-moving': typeof TransportMovingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emergency-services': typeof EmergencyServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/transport-moving': typeof TransportMovingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emergency-services': typeof EmergencyServicesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/transport-moving': typeof TransportMovingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/emergency-services'
    | '/how-it-works'
    | '/transport-moving'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/emergency-services'
    | '/how-it-works'
    | '/transport-moving'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/emergency-services'
    | '/how-it-works'
    | '/transport-moving'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EmergencyServicesRoute: typeof EmergencyServicesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  TransportMovingRoute: typeof TransportMovingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport-moving': {
      id: '/transport-moving'
      path: '/transport-moving'
      fullPath: '/transport-moving'
      preLoaderRoute: typeof TransportMovingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-services': {
      id: '/emergency-services'
      path: '/emergency-services'
      fullPath: '/emergency-services'
      preLoaderRoute: typeof EmergencyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EmergencyServicesRoute: EmergencyServicesRoute,
  HowItWorksRoute: HowItWorksRoute,
  TransportMovingRoute: TransportMovingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
